name              'locustio'
maintainer        'Alain Lefebvre'
maintainer_email  'hartfordfive@gmail.com'
license           'Apache v2.0'
description       'Installs/Configures locust'
long_description  'Installs/Configures locust'
issues_url        'https://github.com/hartfordfive/chef-locust/issues'
source_url        'https://github.com/hartfordfive/chef-locust'
version           '1.0.1'

depends 'poise-python',   '~> 1.2.1'
depends 'apt',            '~> 2.6.1'
depends 'runit',          '~> 1.5.12'
depends 'aws',            '~> 3.3.3'
depends 'firewall',       '~> 2.5.2'

